apiVersion: v1
kind: Service
metadata:
  name: laravel
  labels:
    tier: backend
  namespace: laravel
spec:
  selector:
    app: laravel
    tier: backend
  ports:
    - protocol: TCP
      port: 3000
